### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CarlTheCroissant**
Added guide images

### CODE REVIEW

**Comment by ST-Apps** [comment]
Hi @CarlTheCroissant, would you mind doing an updated version of this one? 
I've added a few things that may be worth showing in the guide.

**Comment by CarlTheCroissant** [comment]
Sure. Tell me what to add! I can redo the old ones if you'd like.

**Comment by CarlTheCroissant** [comment]
@st-apps Sure. Tell me what to add! I can redo the old ones if you'd like. It will be a little while before I can get to my PC, but not too long.

**Comment by ST-Apps** [comment]
Since your first images I've added the ability to snap to existing roads and guidelines, I think that showing them would be enough.
Please refer to #32 and let me know when you have something :)

**Pull request merged**
